---
title: "TabletSwitch_demog"
author: "Bilingual Families Project Team"
date: "9/21/2021"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(dplyr)
library(tidyr)
library(stringr)
```

# read in LEQ data
```{r}
## read in all data in the folder
concordia_eng_LEQ <- read.csv(here("data_LEQ/Concordia_Word-learning Survey(Eng).csv"))

concordia_fr_LEQ <- read.csv(here("data_LEQ/Concordia_Word-learning Survey(Fr).csv"))

princeton_eng_LEQ <- read.csv(here("data_LEQ/Princeton_Word-learning Survey(Eng).csv"))

princeton_sp_LEQ <- read.csv(here("data_LEQ/Princeton_Word-learning Survey(Sp).csv"))
```

# clean dataframes by renaming variables
```{r}
## Concordia: English LEQ
clean_concordia_eng_LEQ <- concordia_eng_LEQ %>%
  #rename variables
  rename(
    subject_id = What.is.your.Participant.ID.,
    filled_by = What.is.your.relationship.to.the.child.who.is.participating.in.our.study.,
    edu_level = What.is.your.highest.level.of.education.,
    which_language_with_child = In.everyday.life..do.you.use.more.English..more.French..or.both.equally.with.your.child..,
    codeswitch_within_sentence = On.a.scale.from.0.to.6...please.rate.how.often.you.switch.between.English.and.French.WITHIN.A.SENTENCE.when.interacting.with.your.child.,
    codeswitch_between_sentence = On.a.scale.from.0.to.6...please.rate.how.often.you.switch.between.English.and.French.BETWEEN.SENTENCES.when.interacting.with.your.child.,
    attend_daycare = Does.your.child.attend.regular.childcare..such.as.daycare..,
    age_since_daycare = If.you.answered..yes..to.the.previous.question..since.what.age.does.your.child.attend.daycare.,
    daycare_language = What.language.s..are.spoken.at.daycare.,
    childname = What.is.your.child.s.name.,
    gender = What.is.your.child.s.gender.,
    ethnicity = What.is.your.child.s.race.ethnicity.,
    fullterm = Was.your.child.full.term..born..37.weeks.gestation..,
    born_at_how_many_weeks = If.you.answered..no..to.the.previous.question..at.how.many.weeks.was.your.child.born.,
    disability = Does.your.child.have.any.vision.or.hearing.problems..language.disability..or.learning.disability.,
    disability_details = If.you.answered.yes.to.the.previous.question..please.explain.the.vision.hearing.problem.or.language.learning.disability.,
    health_problem = Has.your.child.had.any.injuries..illnesses..surgeries.or.ear.infections..,
    health_problem_details = If.you.answered.yes.to.the.previous.question..please.explain.the.illness.injury.surgery.ear.infections.,
    strongest_language = What.is.your.child.s.strongest.language.s..,
    second_strongest_language = What.is.your.child.s.second.strongest.language.s..,
    other_languages = Does.your.child.know.another.language..If.yes..please.list.the.language.s..below.starting.with.the.stronger.language.,
    daily_exposure_eng = On.a.typical.day..right.now..what.percentage.of.the.words.that.your.child.hears.are.in.English.,
    daily_exposure_fr = On.a.typical.day..right.now..what.percentage.of.the.words.that.your.child.hears.are.in.French.,
    daily_exposure_other = On.a.typical.day..right.now..what.percentage.of.the.words.that.your.child.hears.are.in.another.language.,
    global_exposure_eng = If.you.think.about.your.child.s.entire.life..what.percentage.of.the.words.that.your.child.has.heard.are.in.English.,
    global_exposure_fr = If.you.think.about.your.child.s.entire.life..what.percentage.of.the.words.that.your.child.has.heard.are.in.French.,
    global_exposure_other = If.you.think.about.your.child.s.entire.life..what.percentage.of.the.words.that.your.child.has.heard.are.in.another.language.,
    age_of_acquisition_eng = At.what.age.did.your.child.start.learning.English...Enter.0.if.from.birth.,
    speaking_proficiency_eng = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.speaking.English.,
    comprehension_proficiency_eng = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.understanding.spoken.English.,
    age_of_acquisition_fr = At.what.age.did.your.child.start.learning.French...Enter.0.if.from.birth.,
    speaking_proficiency_fr = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.speaking.French.,
    comprehension_proficiency_fr = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.understanding.spoken.French.,
    other_language1 = Does.your.child.know.a.third.language.,
    other_language1_details = What.is.this.language.,
    age_of_acquisition_other1 = At.what.age.did.your.child.start.learning.this.language...Enter.0.if.from.birth.,
    speaking_proficiency_other1 = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.speaking.this.language., 
    comprehension_proficiency_other1 = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.understanding.this.spoken.language.,
    other_language2 = Does.your.child.know.another.language.,
    other_language2_details = What.is.this.language..1,
    age_of_acquisition_other2 = At.what.age.did.your.child.start.learning.this.language...Enter.0.if.from.birth..1,
    speaking_proficiency_other2 = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.speaking.this.language..1,
    comprehension_proficiency_other2 = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.understanding.this.spoken.language..1,
    remarks = Is.there.anything.else.we.need.to.know.about.your.child.s.language.environment.
    ) %>%
  rename_with(~str_replace(., "Does.your.child.have.other.primary.caregivers.", "other_caregivers")) %>%
  rename_with(~str_replace(., "What.is.this.caregiver.s.relationship.to.your.child..e.g...mother..father..aunt..grandfather..nanny..", "additional_caregiver")) %>%
  rename_with(~str_replace(., "What.is.the.highest.level.of.education.achieved.by.this.person.", "additional_caregiver_edu_level")) %>%
  rename_with(~str_replace(., "In.everyday.life..does.this.person.use.more.English..more.French..or.both.equally.with.your.child..", "additional_caregiver_which_language_with_child")) %>%
  rename_with(~str_replace(., "On.a.scale.from.0.to.6...please.rate.how.often.this.person.switches.between.English.and.French.WITHIN.A.SENTENCE.when.interacting.with.your.child.", "additional_caregiver_codeswitch_within_sentence")) %>%
  rename_with(~str_replace(., "On.a.scale.from.0.to.6...please.rate.how.often.this.person.switches.between.English.and.French.BETWEEN.SENTENCES.when.interacting.with.your.child.", "additional_caregiver_codeswitch_between_sentence")) %>%
  # keep only the score in proficiency variables
  mutate_at(vars(matches("proficiency")), ~as.numeric(substr(., 1, 2))) %>%
  # change daily_exposure_other to a numeric variable
  mutate(daily_exposure_other = extract_numeric(daily_exposure_other))

## Concordia: French LEQ
clean_concordia_fr_LEQ <- concordia_fr_LEQ %>%
  #rename variables
  rename(
    subject_id = Quel.est.votre.numéro.d.identification.,
    filled_by = Quelle.est.votre.relation.avec.l.enfant.qui.participe.à.notre.étude.,
    edu_level = Quel.est.votre.plus.haut.niveau.d.éducation.,
    which_language_with_child = Au.quotidien..utilisez.vous.plus.l.anglais..plus.le.français..ou.les.deux.de.façon.égale.avec.votre.enfant.,
    codeswitch_within_sentence = "Sur.une.échelle.de.0.à.6...veuillez.évaluer.la.fréquence.à.laquelle.vous.interchangez.entre.l.anglais.et.le.français.DANS.UNE.MÊME.PHRASE.lorsque.vous.intéragissez.avec.votre.enfant.",
    codeswitch_between_sentence = "Sur.une.échelle.de.0.à.6..veuillez.évaluer.la.fréquence.à.laquelle.vous.interchangez.entre.l.anglais.et.le.français.D.UNE.PHRASE.À.L.AUTRE.lorsque.vous.intéragissez.avec.votre.enfant..",
    attend_daycare = Est.ce.que.votre.enfant.côtoie.régulièrement.un.service.de.garde..tel.qu.une.garderie.,
    age_since_daycare = Si.vous.avez.répondu...oui...à.la.question.précédente..depuis.quel.âge.votre.enfant.côtoie.t.il.un.service.de.garde.,
    daycare_language = Quelle.s..langue.s..est.sont.parlée.s..lorsque.votre.enfant.est.au.service.de.garde.,
    childname = Quel.est.le.prénom.de.votre.enfant.,
    gender = Quel.est.le.sexe.de.votre.enfant.,
    ethnicity = Quelle.est.l.origine.ethnique.de.votre.enfant.,
    fullterm = Votre.enfant.est.il.né.à.terme..né.après.plus.de.37.semaines.de.gestation..,
    born_at_how_many_weeks = Si.vous.avez.répondu...non...à.la.quesiton.précédente..à.combien.de.semaines.votre.enfant.est.il.né.,
    disability = Est.ce.que.votre.enfant.a.des.problèmes.de.vision.ou.d.auditon..un.trouble.du.language..ou.encore.un.trouble.d.apprentissage.,
    disability_details = Si.vous.avez.répondu...oui...à.la.question.précédente..veuillez.expliquer.le.problème.de.vision..d.audition..ou.le.trouble.de.language.ou.d.apprentissage.,
    health_problem = Votre.enfant.a.t.il.déjà.eu.quelque.blessure..maladie.ou.opération.que.ce.soit..ou.encore.une.infection.aux.oreilles.,
    health_problem_details = Si.vous.avez.répondu...oui...à.la.question.précédente..veuillez.expliquer.la.blessure.maladie.opération.infection.,
    strongest_language = Quelle.est.la.ou.les.meilleure.s..langue.s..de.votre.enfant.,
    second_strongest_language =  Quelle.est.la.ou.les.deuxième.s..meilleure.s..langue.s..de.votre.enfant.,
    other_languages = Est.ce.que.votre.enfant.connaît.une.autre.langue..Si.oui..veuillez.indiquer.quelle.s..langue.s..ci.dessous..en.commençant.par.sa.meilleure.langue.,
    daily_exposure_eng = Présentement..lors.d.une.journée.typique..quel.pourcentage.des.mots.que.votre.enfant.entend.est.en.anglais.,
    daily_exposure_fr = Présentement..lors.d.une.journée.typique..quel.pourcentage.des.mots.que.votre.enfant.entend.est.en.français.,
    daily_exposure_other = Présentement..lors.d.une.journée.typique..quel.pourcentage.des.mots.que.votre.enfant.entend.est.dans.une.autre.langue.,
    global_exposure_eng = Si.vous.réfléchissez.à.la.vie.entière.de.votre.enfant..quel.pourcentage.des.mots.que.votre.enfant.a.entendus.est.en.anglais.,
    global_exposure_fr = Si.vous.réfléchissez.à.la.vie.entière.de.votre.enfant..quel.pourcentage.des.mots.que.votre.enfant.a.entendus.est.en.français.,
    global_exposure_other = Si.vous.réfléchissez.à.la.vie.entière.de.votre.enfant..quel.pourcentage.des.mots.que.votre.enfant.a.entendus.est.dans.une.autre.langue.,
    age_of_acquisition_eng = À.quel.âge.votre.enfant.a.t.il.commencé.à.apprendre.l.anglais...Écrire.0.si.dès.la.naissance.,
    speaking_proficiency_eng = "Sur.une.échelle.de.0.à.10..veuillez.indiquer.le.niveau.de.votre.enfant.quant.à.sa.compétence.à.parler.anglais..",
    comprehension_proficiency_eng = "Sur.une.échelle.de.0.à.10..veuillez.indiquer.le.niveau.de.votre.enfant.quant.à.sa.compétence.à.comprendre.l.anglais.parlé.",
    age_of_acquisition_fr = À.quel.âge.votre.enfant.a.t.il.commencé.à.apprendre.le.français...Écrire.0.si.dès.la.naissance.,
    speaking_proficiency_fr = "Sur.une.échelle.de.0.à.10..veuillez.indiquer.le.niveau.de.votre.enfant.quant.à.sa.compétence.à.parler.français.",
    comprehension_proficiency_fr = "Sur.une.échelle.de.0.à.10..veuillez.indiquer.le.niveau.de.votre.enfant.quant.à.sa.compétence.à.comprendre.le.français.parlé.",
    other_language1 = Est.ce.que.votre.enfant.connaît.une.troisième.langue.,
    other_language1_details = Quelle.est.cette.langue.,
    age_of_acquisition_other1 = À.quel.âge.votre.enfant.a.t.il.commencé.à.apprendre.cette.langue...Écrire.0.si.dès.la.naissance.,
    speaking_proficiency_other1 = "Sur.une.échelle.de.0.à.10..veuillez.indiquer.le.niveau.de.votre.enfant.quant.à.sa.compétence.à.parler.cette.langue.", 
    comprehension_proficiency_other1 = "Sur.une.échelle.de.0.à.10..veuillez.indiquer.le.niveau.de.votre.enfant.quant.à.sa.compétence.à.comprendre.cette.langue.lorsque.parlée.",
    other_language2 = Est.ce.que.votre.enfant.connaît.une.autre.langue.,
    other_language2_details = Quelle.est.cette.langue..1,
    age_of_acquisition_other2 = À.quel.âge.votre.enfant.a.t.il.commencé.à.apprendre.cette.langue...Écrire.0.si.dès.la.naissance..1,
    speaking_proficiency_other2 = "Sur.une.échelle.de.0.à.10..veuillez.indiquer.le.niveau.de.votre.enfant.quant.à.sa.compétence.à.parler.cette.langue..1",
    comprehension_proficiency_other2 = "Sur.une.échelle.de.0.à.10..veuillez.indiquer.le.niveau.de.votre.enfant.quant.à.sa.compétence.à.comprendre.cette.langue.lorsque.parlée..1",
    remarks = Y.a.t.il.autre.chose.que.nous.devrions.savoir.quant.à.l.environnement.linguistique.de.votre.enfant.
    ) %>%
  rename_with(~str_replace(., "Est.ce.qu.une.autre.personne.est.également.responsable.de.votre.enfant.", "other_caregivers")) %>%
  rename_with(~str_replace(., "Quelle.est.la.relation.de.cette.personne.avec.votre.enfant..ex..mère..père..tante..grand.père..nounou..", "additional_caregiver")) %>%
  rename_with(~str_replace(., "Quel.est.le.plus.haut.niveau.d.éducation.atteint.par.cette.personne.", "additional_caregiver_edu_level")) %>%
  rename_with(~str_replace(., "Au.quotidien..cette.personne.utilise.t.telle.plus.l.anglais..plus.le.français..ou.les.deux.de.façon.égale.avec.votre.enfant.", "additional_caregiver_which_language_with_child")) %>%
  rename_with(~str_replace(., "Sur.une.échelle.de.0.à.6...veuillez.évaluer.la.fréquence.à.laquelle.cette.personne.interchange.entre.l.anglais.et.le.français.DANS.UNE.MÊME.PHRASE.lorsque.qu.elle.intéragit.avec.votre.enfant..", "additional_caregiver_codeswitch_within_sentence")) %>%
  rename_with(~str_replace(., "Sur.une.échelle.de.0.à.6..veuillez.évaluer.la.fréquence.à.laquelle.cette.personne.interchange.entre.l.anglais.et.le.français.D.UNE.PHRASE.À.L.AUTRE.lorsqu.elle.intéragit.avec.votre.enfant..", "additional_caregiver_codeswitch_between_sentence")) %>%
  # keep only the score in proficiency variables
  mutate_at(vars(matches("proficiency")), ~as.numeric(substr(.,1, 2))) 


## Princeton: English LEQ
clean_princeton_eng_LEQ <- princeton_eng_LEQ %>%
  #rename variables
  rename(
    subject_id = What.is.your.Participant.ID.,
    filled_by = What.is.your.relationship.to.the.child.who.is.participating.in.our.study.,
    edu_level = What.is.your.highest.level.of.education.,
    which_language_with_child = In.everyday.life..do.you.use.more.English..more.Spanish..or.both.equally.with.your.child..,
    codeswitch_within_sentence = On.a.scale.from.0.to.6...please.rate.how.often.you.switch.between.English.and.Spanish.WITHIN.A.SENTENCE.when.interacting.with.your.child.,
    codeswitch_between_sentence = On.a.scale.from.0.to.6...please.rate.how.often.you.switch.between.English.and.Spanish.BETWEEN.SENTENCES.when.interacting.with.your.child.,
    attend_daycare = Does.your.child.attend.regular.childcare..such.as.daycare..,
    age_since_daycare = If.you.answered..yes..to.the.previous.question..since.what.age.does.your.child.attend.daycare.,
    daycare_language = What.language.s..are.spoken.at.daycare.,
    childname = What.is.your.child.s.name.,
    gender = What.is.your.child.s.gender.,
    ethnicity = What.is.your.child.s.race.ethnicity.,
    fullterm = Was.your.child.full.term..born..37.weeks.gestation..,
    born_at_how_many_weeks = If.you.answered..no..to.the.previous.question..at.how.many.weeks.was.your.child.born.,
    disability = Does.your.child.have.any.vision.or.hearing.problems..language.disability..or.learning.disability.,
    disability_details = If.you.answered.yes.to.the.previous.question..please.explain.the.vision.hearing.problem.or.language.learning.disability.,
    health_problem = Has.your.child.had.any.injuries..illnesses..surgeries.or.ear.infections..,
    health_problem_details = If.you.answered.yes.to.the.previous.question..please.explain.the.illness.injury.surgery.ear.infections.,
    strongest_language = What.is.your.child.s.strongest.language.s..,
    second_strongest_language = What.is.your.child.s.second.strongest.language.s..,
    other_languages = Does.your.child.know.another.language..If.yes..please.list.the.language.s..below.starting.with.the.stronger.language.,
    daily_exposure_eng = On.a.typical.day..right.now..what.percentage.of.the.words.that.your.child.hears.are.in.English.,
    daily_exposure_sp = On.a.typical.day..right.now..what.percentage.of.the.words.that.your.child.hears.are.in.Spanish.,
    daily_exposure_other = On.a.typical.day..right.now..what.percentage.of.the.words.that.your.child.hears.are.in.another.language.,
    global_exposure_eng = If.you.think.about.your.child.s.entire.life..what.percentage.of.the.words.that.your.child.has.heard.are.in.English.,
    global_exposure_sp = If.you.think.about.your.child.s.entire.life..what.percentage.of.the.words.that.your.child.has.heard.are.in.Spanish.,
    global_exposure_other = If.you.think.about.your.child.s.entire.life..what.percentage.of.the.words.that.your.child.has.heard.are.in.another.language.,
    age_of_acquisition_eng = At.what.age.did.your.child.start.learning.English...Enter.0.if.from.birth.,
    speaking_proficiency_eng = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.speaking.English.,
    comprehension_proficiency_eng = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.understanding.spoken.English.,
    age_of_acquisition_sp = At.what.age.did.your.child.start.learning.Spanish...Enter.0.if.from.birth.,
    speaking_proficiency_sp = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.speaking.Spanish.,
    comprehension_proficiency_sp = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.understanding.spoken.Spanish.,
    other_language1 = Does.your.child.know.a.third.language.,
    other_language1_details = What.is.this.language.,
    age_of_acquisition_other1 = At.what.age.did.your.child.start.learning.this.language...Enter.0.if.from.birth.,
    speaking_proficiency_other1 = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.speaking.this.language., 
    comprehension_proficiency_other1 = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.understanding.this.spoken.language.,
    other_language2 = Does.your.child.know.another.language.,
    other_language2_details = What.is.this.language..1,
    age_of_acquisition_other2 = At.what.age.did.your.child.start.learning.this.language...Enter.0.if.from.birth..1,
    speaking_proficiency_other2 = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.speaking.this.language..1,
    comprehension_proficiency_other2 = On.a.scale.of.0.to.10..please.select.your.child.s.level.of.proficiency.in.understanding.this.spoken.language..1,
    remarks = Is.there.anything.else.we.need.to.know.about.your.child.s.language.environment.
    ) %>%
  rename_with(~str_replace(., "Does.your.child.have.other.primary.caregivers.", "other_caregivers")) %>%
  rename_with(~str_replace(., "What.is.this.caregiver.s.relationship.to.your.child..e.g...mother..father..aunt..grandfather..nanny..", "additional_caregiver")) %>%
  rename_with(~str_replace(., "What.is.the.highest.level.of.education.achieved.by.this.person.", "additional_caregiver_edu_level")) %>%
  rename_with(~str_replace(., "In.everyday.life..does.this.person.use.more.English..more.Spanish..or.both.equally.with.your.child..", "additional_caregiver_which_language_with_child")) %>%
  rename_with(~str_replace(., "On.a.scale.from.0.to.6...please.rate.how.often.this.person.switches.between.English.and.Spanish.WITHIN.A.SENTENCE.when.interacting.with.your.child.", "additional_caregiver_codeswitch_within_sentence")) %>%
  rename_with(~str_replace(., "On.a.scale.from.0.to.6...please.rate.how.often.this.person.switches.between.English.and.Spanish.BETWEEN.SENTENCES.when.interacting.with.your.child.", "additional_caregiver_codeswitch_between_sentence")) %>%
  # keep only the score in proficiency variables
  mutate_at(vars(matches("proficiency")), ~as.numeric(substr(.,1, 2))) 


## Princeton: Spanish LEQ
clean_princeton_sp_LEQ <- princeton_sp_LEQ %>%
  #rename variables
  rename(
    subject_id = X.Cuál.es.su.ID.como.participante.,
    filled_by = X.Cuál.es.su.relación.con.el.niño.a..que.está.participando.en.nuestro.estudio.,
    edu_level = X.Cuál.es.el.nivel.más.alto.de.educación.que.ha.logrado.usted.,
    which_language_with_child = X.En.la.vida.diaria...habla.más.inglés..más.español.o.ambos.igualmente.,
    codeswitch_within_sentence = En.una.escala.del.0.al.6..por.favor..evalúe.con.que.frecuencia.usted.cambia.entre.inglés.y.español.DENTRO.DE.una.misma.frase.cuando.habla.con.su.hijo.a..,
    codeswitch_between_sentence = En.una.escala.del.0.al.6..por.favor..evalúe.con.que.frecuencia.usted.cambia.entre.inglés.y.español.ENTRE.frases.cuando.habla.con.su.hijo.a..,
    attend_daycare = X.Asiste.su.hijo.a..a.la.guardería.,
    age_since_daycare = X.Si.respondió..sí..a.la.pregunta.anterior...desde.qué.edad.asiste.su.hijo.a..a.la.guardería..,
    daycare_language = X.Qué.idiomas.hablan.en.la.guardería.,
    #childname = What.is.your.child.s.name.,
    gender = X.Cuál.es.el.género.de.su.hijo.a..,
    ethnicity = X.Cuál.es.la.raza.étnia.de.su.hijo.a..,
    fullterm = X.Nació.su.hijo.a..a.término..nacido...37.semanas.de.gestación..,
    born_at_how_many_weeks = Si.respondió..no..a.la.pregunta.anterior..cuantas.semanas.duró.su.embarazo.,
    disability = X.Tiene.su.hijo.a..algún.problema.de.visión.u.audición.,
    disability_details = X.Si.respondió..sí..a.la.pregunta.anterior..por.favor..explique.el.problema.de.visión.audición.,
    health_problem = X.Ha.tenido.su.hijo.a..alguna.lesión..enfermedad..cirugía.o.infecciones.del.oído.,
    health_problem_details = X.Si.respondió..sí..a.la.pregunta.anterior..por.favor..explique.la.lesion.cirguía.infección.,
    strongest_language = X.Qué.idioma.es.más.dominante.en.su.hijo.a..,
    second_strongest_language = X.Qué.idioma.es.el.segundo.más.dominante.en.su.hijo.a..,
    other_languages = Sabe.su.hijo.a..algún.otro.idioma...Si.respondió..sí..a.la.pregunta..por.favor..enumérelos.en.el.apartado.inferior..empezando.por.el.idioma.más.dominante..,
    daily_exposure_eng = En.un.día.típico..actualmente...qué.porcentaje.de.las.palabras.que.su.hijo.a..escucha.son.en.inglés.,
    daily_exposure_sp = En.un.día.típico..actualmente...qué.porcentaje.de.las.palabras.que.su.hijo.a..escucha.son.en.español.,
    daily_exposure_other = En.un.día.típico..actualmente...qué.porcentaje.de.las.palabras.que.su.hijo.a..escucha.son.en.otro.idioma.,
    global_exposure_eng = Si.usted.piensa.en.toda.la.vida.de.su.hijo.a...qué.porcentaje.de.las.palabras.que.su.hijo.a..ha.escuchado.son.en.inglés.,
    global_exposure_sp = Si.usted.piensa.en.toda.la.vida.de.su.hijo.a...qué.porcentaje.de.las.palabras.que.su.hijo.a..ha.escuchado.son.en.español.,
    global_exposure_other = Si.usted.piensa.en.toda.la.vida.de.su.hijo.a....qué.porcentaje.de.las.palabras.que.su.hijo.a..ha.escuchado.son.en.otro.idioma.,
    age_of_acquisition_eng = X.A.qué.edad.empezó.su.hijo.a..a.aprender.inglés...ponga.0.si.inglés.es.su.idioma.nativo.desde.el.nacimiento.,
    speaking_proficiency_eng = En.una.escala.del.0.al.10..por.favor..elija.el.nivel.de.competencia.que.tiene.su.hijo.a..hablando.inglés..,
    comprehension_proficiency_eng = En.una.escala.del.0.al.10..por.favor..elija.el.nivel.de.competencia.de.su.hijo.a..entendiendo.a.una.persona.hablando.inglés..,
    age_of_acquisition_sp = X.A.qué.edad.empezó.su.hijo.a..a.aprender.español...ponga.0.si.español.es.su.idioma.nativo.desde.el.nacimiento.,
    speaking_proficiency_sp = En.una.escala.del.0.al.10..por.favor..elija.el.nivel.de.competencia.de.su.hijo.a..hablando.español..,
    comprehension_proficiency_sp = En.una.escala.del.0.al.10..por.favor..elija.el.nivel.de.competencia.de.su.hijo.a..entendiendo.a.una.persona.hablando.español..,
    other_language1 = X.Sabe.su.hijo.a..otro.idioma.,
    other_language1_details = X.Qué.idioma.es.,
    age_of_acquisition_other1 = X.A.qué.edad.empezó.su.hijo.a..a.aprender.este.idioma...ponga.0.si.es.su.idioma.nativo.desde.el.nacimiento.,
    speaking_proficiency_other1 = En.una.escala.de.0.al.10..por.favor..elija.el.nivel.de.la.competencia.de.su.hijo.a..hablando.este.idioma.., 
    comprehension_proficiency_other1 = En.una.escala.del.0.al.10..por.favor..elija.el.nivel.de.competencia.de.su.hijo.a..entendiendo.a.una.persona.hablando.este.idioma..,
    other_language2 = X.Sabe.su.hijo.a..otro.idioma..1,
    other_language2_details = X.Qué.idioma.es..1,
    age_of_acquisition_other2 = X.A.qué.edad.empezó.su.hijo.a..a.aprender.este.idioma...ponga.0.si.es.su.idioma.nativo.desde.el.nacimiento..1,
    speaking_proficiency_other2 = En.una.escala.del.0.al.10..por.favor..elija.el.nivel.de.competencia.de.su.hijo.a..hablando.este.idioma..,
    comprehension_proficiency_other2 = En.una.escala.de.0.al.10..por.favor..elija.el.nivel.de.competencia.de.su.hijo.a..entendiendo.a.una.persona.hablando.este.idioma..,
    remarks = X.Hay.algo.más.que.debamos.saber.sobre.el.entorno.lingüístico.infantil.de.su.hijo.a...los.idiomas.que.conoce.o.a.los.que.está.expuesto.
    ) %>%
  rename_with(~str_replace(., "X.Tiene.su.hijo.a..otros.cuidadores.principales.", "other_caregivers")) %>%
  rename_with(~str_replace(., "X..Cuál.es.la.relación.del.cuidador.con.su.hijo.a....p..ej..madre..padre..tía..abuelo..niñera..", "additional_caregiver")) %>%
  rename_with(~str_replace(., "X.Cuál.es.el.nivel.de.educación.más.alto.logrado.por.esta.persona.", "additional_caregiver_edu_level")) %>%
  rename_with(~str_replace(., "X.En.la.vida.diaria...habla.esta.persona.más.inglés..más.español.o.ambos.igualmente.con.su.hijo.a..", "additional_caregiver_which_language_with_child")) %>%
  rename_with(~str_replace(., "En.una.escala.del.0.al.6..por.favor..evalúe.con.que.frecuencia.esta.persona.cambia.entre.inglés.y.español.DENTRO.DE.una.misma.frase.cuando.habla.con.su.hijo.a..", "additional_caregiver_codeswitch_within_sentence")) %>%
  rename_with(~str_replace(., "En.una.escala.del.0.al.6..por.favor..evalúe.con.que.frecuencia.esta.persona.cambia.entre.inglés.y.español.ENTRE.frases.cuando.habla.con.su.hijo.a..", "additional_caregiver_codeswitch_between_sentence")) %>%
  # keep only the score in proficiency variables
  mutate_at(vars(matches("proficiency")), ~as.numeric(substr(.,1, 2))) %>%
  rename(additional_caregiver_which_language_with_child.2 = additional_caregiver_which_language_with_child.1, 
         additional_caregiver_which_language_with_child.1 = X.En.la.vida.diaria...habla.esta.persona.más.inglés..más.español.o.ambos.igualmente..cuando.habla.con.su.hijo.a..,
         additional_caregiver.2 = X..Cuál.es.la.relación.del.cuidador.a.su.hijo.a....p..ej..madre..padre..tía..abuelo..niñera..) %>%
  # correct parent's response
  mutate_at(vars(matches("age_of_acquisition")), funs(ifelse(. == "Desde que nacio", 0, .))) %>%
  mutate_at(vars(matches("age_of_acquisition")), ~as.numeric(substr(.,1, 2)))

```

# merge all datasets 
```{r}
concordia_LEQ <- full_join(clean_concordia_eng_LEQ, clean_concordia_fr_LEQ)

princeton_LEQ <- full_join(clean_princeton_eng_LEQ, clean_princeton_sp_LEQ)

combined_LEQ <- full_join(concordia_LEQ, clean_princeton_eng_LEQ)
```

# check exclusion criteria
```{r}
# preterm?
combined_LEQ %>%
  select(subject_id, fullterm, born_at_how_many_weeks) %>%
  filter(born_at_how_many_weeks < 37)

# vision, hearing, or language problems? (checked and can keep all of them for now)
combined_LEQ %>%
  select(subject_id, disability, disability_details) %>%
  filter(disability == "Yes" | disability == "Oui" | disability == "Sí")

# health problem? (checked and can keep all of them for now)
combined_LEQ %>%
  select(subject_id, health_problem, health_problem_details) %>%
  filter(health_problem == "Yes" | health_problem == "Oui" | health_problem == "Sí")

# Comprehension proficiency
check <- combined_LEQ %>%
  select(subject_id, matches("comprehension_proficiency")) %>%
  filter(comprehension_proficiency_eng < 7 | comprehension_proficiency_fr < 7 | comprehension_proficiency_sp < 7) %>%
  select(-matches("other"))

# add exluscion criteria to data frame
exclusion_LEQ <- combined_LEQ %>%
  # add new exclusion variables
  mutate(
    ## preterm
    exclude_preterm = case_when(born_at_how_many_weeks < 37 ~ 1,
                        TRUE ~ 0), # 1 = preterm and to be exclude; 0 = fullterm
    ## vision, hearing, or language problems
    exclude_disability = if_else(disability == "Yes" | disability == "Oui" | disability == "Sí", 1, 0),
    exclude_health = if_else(health_problem == "Yes" | health_problem == "Oui" | health_problem == "Sí", 1, 0),
    ## proficiency level (if both languages are >= 7/10, then high; if one language is < 7/10, then low)
    proficiency_level = case_when(
      comprehension_proficiency_eng >= 7 & comprehension_proficiency_fr >= 7 | comprehension_proficiency_eng >= 7 & comprehension_proficiency_sp >= 7 ~ "high",
      TRUE ~ "low"
      )
    )  %>%
  # keep only relevant variables
  select(subject_id, exclude_preterm, exclude_disability, exclude_health, 
         comprehension_proficiency_eng, comprehension_proficiency_fr, comprehension_proficiency_sp, proficiency_level)

# save the exclusion data
write.csv(exclusion_LEQ, here("output/exclusion_LEQ.csv"), row.names=F)
```
